package three;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;
import java.util.Vector;

public class BudgetEntries {
    private JPanel rep;
    private JPanel sum;
    private JTable tableEnt;
    private JFrame frameEnt;
    private Connection con = null;
    private Statement st = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;
    private String monYr;
    private String[] columnNames = {"Month-Year", "Salary", "Other Income", "Groceries", "Rent/Mortgage", "Utilities", "Miscellaneous"};

    public void monReport() {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {


                try {
                    Class.forName("org.sqlite.SQLiteJDBCLoader");
                    con = DriverManager.getConnection("jdbc:sqlite:budget_tracker.identifier.sqlite");
                    st = con.createStatement();
                    rs = st.executeQuery("SELECT * FROM monthly_budget");
                    Vector v = new Vector();
                    while (rs.next()) {
                        monYr = rs.getString(1);
                        v.add(monYr);
                    }
                    st.close();
                    rs.close();
                } catch (Exception e) {
                }

                showTableData();
            }
        });
    }

    public void showTableData() {

        frameEnt = new JFrame("Monthly Budget");
        frameEnt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frameEnt.setLayout(new BorderLayout());
        frameEnt.setLocationRelativeTo(null);

        //TableModel tm = new TableModel();
        //DefaultTableModel model = new DefaultTableModel(tm.getData1(), tm.getColumnNames());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnNames);

        //table = new JTable(model);
        tableEnt = new JTable();
        tableEnt.setModel(model);
        tableEnt.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableEnt.setFillsViewportHeight(true);
        JScrollPane scroll = new JScrollPane(tableEnt);
        scroll.setHorizontalScrollBarPolicy(
                JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scroll.setVerticalScrollBarPolicy(
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

        //String textvalue = textbox.getText();
        String monYear = "";
        String monSal = "";
        String monOI = "";
        String monFood = "";
        String monRent = "";
        String monUtil = "";
        String monMisc = "";

        try {
            pst = con.prepareStatement("SELECT * FROM monthly_budget WHERE monYr");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                monYear = rs.getString("monYr");
                monSal = rs.getString("salary");
                monOI = rs.getString("otherIncome");
                monFood = rs.getString("groceries");
                monRent = rs.getString("rent");
                monUtil = rs.getString("utilities");
                monMisc = rs.getString("misc");
                model.addRow(new Object[]{monYear, monSal, monOI, monFood, monRent, monUtil, monMisc});
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        frameEnt.add(scroll);
        frameEnt.setVisible(true);
        frameEnt.setSize(600, 250);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rep = new JPanel();
        rep.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        sum = new JPanel();
        sum.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        rep.add(sum, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rep;
    }
}
